"""create_initial_schema

Revision ID: 99b1401cc03b
Revises: 
Create Date: 2026-09-18 14:38:53.441671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b1401cc03b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nearby_places_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nearby_places_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nearby_places_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_nearby_places_cache_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.Column('guest_rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('cancellation_policy', sa.String(length=255), nullable=True),
    sa.Column('eco_certified', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotels_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotels_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotels_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotels_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotels_name'), ['name'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_id'), ['id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bed_configuration', sa.String(length=100), nullable=True),
    sa.Column('max_occupancy', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('taxes_and_fees', sa.Float(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('free_cancellation', sa.Boolean(), nullable=True),
    sa.Column('breakfast_included', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.String(length=20), nullable=False),
    sa.Column('check_out', sa.String(length=20), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('adults_count', sa.Integer(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('children_ages', sa.JSON(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('base_total', sa.Float(), nullable=False),
    sa.Column('taxes_total', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('itemized_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('guest_phone', sa.String(length=50), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_reference'), ['booking_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)

    op.create_table('room_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('available_units', sa.Integer(), nullable=True),
    sa.Column('price_override', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_availability_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_availability_id'), ['id'], unique=False)

    op.create_table('email_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_notifications_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_notifications_email_type'), ['email_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_notifications_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_notifications_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_signature', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_email_notifications_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_email_notifications_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_email_notifications_email_type'))
        batch_op.drop_index(batch_op.f('ix_email_notifications_booking_id'))

    op.drop_table('email_notifications')
    with op.batch_alter_table('room_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_availability_id'))
        batch_op.drop_index(batch_op.f('ix_room_availability_date'))

    op.drop_table('room_availability')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_reference'))

    op.drop_table('bookings')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotels_name'))
        batch_op.drop_index(batch_op.f('ix_hotels_longitude'))
        batch_op.drop_index(batch_op.f('ix_hotels_latitude'))
        batch_op.drop_index(batch_op.f('ix_hotels_id'))
        batch_op.drop_index(batch_op.f('ix_hotels_country'))
        batch_op.drop_index(batch_op.f('ix_hotels_city'))

    op.drop_table('hotels')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('nearby_places_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nearby_places_cache_id'))
        batch_op.drop_index(batch_op.f('ix_nearby_places_cache_cache_key'))

    op.drop_table('nearby_places_cache')
    # ### end Alembic commands ###
